services:
  mineos:
    image: hexparrot/mineos:latest
    container_name: mineos
    restart: unless-stopped
    ports:
      - "8443:8443"  # Web interface
      - "25565:25565"  # Minecraft server port
      - "25575:25575"  # RCON port
    volumes:
      - mineos_data:/var/games/minecraft
      - ./backups:/var/games/minecraft/backups
      - ./maps:/var/games/minecraft/maps
    environment:
      - TZ=UTC
    networks:
      - minecraft-network

volumes:
  mineos_data:
    driver: local

networks:
  minecraft-network:
    driver: bridge
